version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: mydb1
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  # Python Application
  app:
    build: .
    container_name: python_app
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=mydb1
      - DB_USER=root
      - DB_PASSWORD=123456
    ports:
      - "5000:5000"
    networks:
      - app_network
    volumes:
      - .:/app
    command: python app.py

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge
